"""Write the installer's licence page from EULA.md.

    python scripts/make_installer_license.py

The Windows installer shows a plain-text licence with an "I Agree" button;
EULA.md is the one source, so this strips its Markdown into
desktop/installer/EULA.txt (git-ignored, regenerated by desktop/build.ps1).
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "EULA.md"
OUT = ROOT / "desktop" / "installer" / "EULA.txt"


def to_text(md: str) -> str:
    lines = []
    for line in md.splitlines():
        heading = re.match(r"^(#+)\s+(.*)$", line)
        if heading:
            title = heading.group(2).strip()
            lines.append(title.upper() if len(heading.group(1)) == 1 else title)
            continue
        line = re.sub(r"\*\*(.+?)\*\*", r"\1", line)
        line = re.sub(r"`(.+?)`", r"\1", line)
        lines.append(line)
    text = "\n".join(lines).strip() + "\n"
    # NSIS shows the file in the system ANSI code page: keep it ASCII.
    for a, b in (("\u2014", "-"), ("\u2013", "-"), ("\u2019", "'"), ("\u201c", '"'), ("\u201d", '"'), ("\u00a9", "(c)")):
        text = text.replace(a, b)
    return text.encode("ascii", "replace").decode("ascii")


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(to_text(SRC.read_text(encoding="utf-8")), encoding="ascii", newline="\r\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
